### ISSUE TITLE
Drink SWA Checkout not working Issue

### ISSUE THREAD

**Issue by Akdex** [farzi-engineer/farzicom-roadmap#1] opened 2021-12-22 12:42 UTC
![DrinkSWA oreder placing issue ](https://user-images.githubusercontent.com/49723359/147094386-25a99cac-e3c0-4e13-adae-1e909d2bab77.PNG)

Taking Longer time than usual

**Comment by deathping1994** [comment] 2021-12-22 14:00
Whats the reason? can you check the console and share the response ? that can help diagnose the problem.

**Comment by soham2710** [comment] 2021-12-23 11:19
The website hanged out and on checking out the cart it took longer time to load. Hence we reported the issue.

**Comment by deathping1994** [comment] 2021-12-23 14:47
Closing since it's not reproducible. Feel free to open the issue again if the issue is replicable.

**Closed as completed by deathping1994** 2021-12-23 14:47 UTC
